name: huawei_nextjs

on: 
push: 
  branches: [$development]
pull_request:
  branches: [$development]
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Eslint
        run: npm run lint -- --fix  

      - name: Test
        run: npm run test
              
      - name: Build
        run: npm run build
      
